version: '3'

services:
  backend:
    build: ./backend
    expose:
      - 8080
    env_file:
      - ./backend/.local.env
    networks:
      - app-network
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - app-network

  traefik:  # new
    image: traefik:v2.10
    ports:
      - 80:80
      - 8081:8080
    volumes:
      - "./traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  frontend:
    build:
      context: ./frontend
    expose:
      - 3000
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app/frontend

networks:
  app-network:

